project:
  type: website
  output-dir: docs

website:
  title: "Claire Whiting"
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - text: CV
        file: cv.pdf
      - posts.qmd
      - icon: github
        href: https://github.com/claire-whiting
      - icon: twitter
        href: https://twitter.com/claire_whiting
  page-footer: 
    background: light
    left: 
      - icon: github
        href: https://github.com/claire-whiting
      - icon: twitter
        href: https://twitter.com/claire_whiting

format:
  html:
    page-layout: full
    theme: greenstyle.css
    mainfont: Poppins
    toc: true

editor: visual


